# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from hskw import hskw_pb2 as hskw_dot_hskw__pb2


class SnappyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatedCaption = channel.unary_unary(
            "/Snappy/CreatedCaption",
            request_serializer=hskw_dot_hskw__pb2.CreatedCaptionRequest.SerializeToString,
            response_deserializer=hskw_dot_hskw__pb2.CreatedCaptionResponse.FromString,
        )
        self.CreatedQuestion = channel.unary_unary(
            "/Snappy/CreatedQuestion",
            request_serializer=hskw_dot_hskw__pb2.CreatedQuestionRequest.SerializeToString,
            response_deserializer=hskw_dot_hskw__pb2.CreatedQuestionResponse.FromString,
        )


class SnappyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatedCaption(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreatedQuestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SnappyServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "CreatedCaption": grpc.unary_unary_rpc_method_handler(
            servicer.CreatedCaption,
            request_deserializer=hskw_dot_hskw__pb2.CreatedCaptionRequest.FromString,
            response_serializer=hskw_dot_hskw__pb2.CreatedCaptionResponse.SerializeToString,
        ),
        "CreatedQuestion": grpc.unary_unary_rpc_method_handler(
            servicer.CreatedQuestion,
            request_deserializer=hskw_dot_hskw__pb2.CreatedQuestionRequest.FromString,
            response_serializer=hskw_dot_hskw__pb2.CreatedQuestionResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "Snappy", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Snappy(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatedCaption(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/Snappy/CreatedCaption",
            hskw_dot_hskw__pb2.CreatedCaptionRequest.SerializeToString,
            hskw_dot_hskw__pb2.CreatedCaptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def CreatedQuestion(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/Snappy/CreatedQuestion",
            hskw_dot_hskw__pb2.CreatedQuestionRequest.SerializeToString,
            hskw_dot_hskw__pb2.CreatedQuestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
